// x402 payment layer for VEY1 — single source of truth using the official OKX SDK.
//
// This file is the ONLY place in the codebase that constructs x402 challenges,
// PAYMENT-REQUIRED headers, or PAYMENT-SIGNATURE verification.
//
// Architecture:
//   1. ONE payment layer instance per process
//   2. Protects EVERY paid endpoint through a single RoutesConfig
//   3. All 402 challenges, PAYMENT-REQUIRED headers, and verification are
//      generated by the OKX SDK — NO manual implementation
//   4. If required env vars are missing, the application MUST fail to start

import type { RequestHandler, Response } from "express";
import { OKXFacilitatorClient } from "@okxweb3/x402-core";
import { ExactEvmScheme } from "@okxweb3/x402-evm/exact/server";
import {
  paymentMiddlewareFromHTTPServer,
  setSettlementOverrides,
  x402HTTPResourceServer,
  x402ResourceServer,
} from "@okxweb3/x402-express";
import { config } from "../config/secrets.js";

const NETWORK = (process.env.X402_NETWORK ?? "eip155:196") as `eip155:${string}`;
const USDT0_ADDRESS =
  process.env.X402_ASSET ?? "0x779ded0c9e1022225f8e0630b35a9b54be713736";
const AGENT_NAME = "VEY1";

/**
 * Build the x402 payment layer. THROWS if required env vars are missing.
 * The application must never start in production with payments disabled.
 */
export function buildPaymentLayer(): {
  middleware: RequestHandler;
  initialize: () => Promise<void>;
} {
  const apiKey = process.env.OKX_FACILITATOR_API_KEY;
  const secretKey = process.env.OKX_FACILITATOR_SECRET_KEY;
  const passphrase = process.env.OKX_FACILITATOR_PASSPHRASE;
  const missing: string[] = [];
  if (!apiKey) missing.push("OKX_FACILITATOR_API_KEY");
  if (!secretKey) missing.push("OKX_FACILITATOR_SECRET_KEY");
  if (!passphrase) missing.push("OKX_FACILITATOR_PASSPHRASE");
  if (missing.length > 0) {
    throw new Error(
      `x402 payment layer cannot start: missing env vars ${missing.join(", ")}. ` +
        `Set these in the deployment environment. The application must never ` +
        `start with payments disabled.`
    );
  }
  if (!config.x402.receivingWallet) {
    throw new Error(
      "x402 payment layer cannot start: X402_RECEIVING_WALLET is not set. " +
        "Set this in the deployment environment to your X Layer receiving address."
    );
  }

  const facilitator = new OKXFacilitatorClient({
    apiKey: apiKey!,
    secretKey: secretKey!,
    passphrase: passphrase!,
    baseUrl: process.env.OKX_FACILITATOR_BASE_URL ?? "https://web3.okx.com",
    // syncSettle: false — fire-and-forget settlement. The OKX facilitator
    // /settle endpoint hangs from some egress IPs (Cloudflare 1010). Async
    // settlement means the response goes out as soon as verify accepts the
    // signature, and the on-chain settlement completes in the background.
    syncSettle: false,
  });

  const resourceServer = new x402ResourceServer(facilitator).register(
    NETWORK,
    new ExactEvmScheme(),
  );

  // Pre-populate the supported-kinds cache with the eip155:196 / exact kind
  // so the SDK never needs to call getSupported() on the IP-blocked OKX
  // facilitator. This is the documented workaround for the Cloudflare 1010
  // block on the /api/v6/pay/x402/supported endpoint.
  const fakeSupportedResponse = {
    kinds: [
      {
        x402Version: 2,
        scheme: "exact",
        network: NETWORK,
        extra: { name: "USD₮0", version: "1" },
      },
    ],
  };
  const networkMap = new Map<string, Map<string, unknown>>();
  const schemeMap = new Map<string, unknown>();
  schemeMap.set("exact", fakeSupportedResponse);
  networkMap.set(NETWORK, schemeMap);
  const versionMap = new Map<number, Map<string, Map<string, unknown>>>();
  versionMap.set(2, networkMap);
  (resourceServer as unknown as {
    supportedResponsesMap: typeof versionMap;
  }).supportedResponsesMap = versionMap;
  (resourceServer as unknown as {
    facilitatorClientsMap: Map<number, Map<string, Map<string, unknown>>>;
  }).facilitatorClientsMap = new Map([
    [2, new Map([[NETWORK, new Map([["exact", facilitator]])]])],
  ]);

  const feeAtomic = String(Math.round(config.x402.auditPrice * 1_000_000));
  const accepts = {
    scheme: "exact" as const,
    network: NETWORK,
    payTo: config.x402.receivingWallet,
    price: {
      asset: USDT0_ADDRESS,
      amount: feeAtomic,
      extra: { name: "USD₮0", version: "1", decimals: 6 },
    },
    maxTimeoutSeconds: 300,
  };

  // ONE RoutesConfig. The SDK is the single source of truth for every
  // protected endpoint. It generates the 402 challenge, sets the
  // PAYMENT-REQUIRED header, and verifies the PAYMENT-SIGNATURE on
  // paid requests — all automatically.
  const httpServer = new x402HTTPResourceServer(resourceServer, {
    "POST /v1/audit": {
      accepts,
      description: `${AGENT_NAME}: forensic crypto project audit (12-18 page PDF)`,
      mimeType: "application/json",
    },
    "GET /v1/audit": {
      accepts,
      description: `${AGENT_NAME}: forensic crypto project audit (12-18 page PDF)`,
      mimeType: "application/json",
    },
    "POST /mcp": {
      accepts,
      description: `${AGENT_NAME} MCP: forensic crypto project audit (A2MCP transport)`,
      mimeType: "application/json",
    },
  });

  // MCP A2MCP spec: initialize, tools/list, ping, notifications/initialized
  // are FREE handshake methods. Only tools/call requires payment. We use
  // onProtectedRequest to grant free access to those handshake methods
  // on the /mcp route.
  httpServer.onProtectedRequest(async (context) => {
    try {
      const adapter = context.adapter as { getBody?: () => unknown };
      const body = adapter.getBody?.();
      if (body && typeof body === "object" && "method" in body) {
        const method = String((body as { method?: unknown }).method ?? "");
        if (
          method === "initialize" ||
          method === "tools/list" ||
          method === "ping" ||
          method === "notifications/initialized"
        ) {
          return { grantAccess: true };
        }
      }
    } catch {
      // If we cannot parse the body, fall through to the standard payment check.
    }
    return;
  });

  // SDK is the ONLY source of truth. No custom wrapper, no manual headers,
  // no manual 402 generation. The SDK generates every 402 challenge +
  // PAYMENT-REQUIRED + X-PAYMENT-RESPONSE header from RoutesConfig.
  const middleware = paymentMiddlewareFromHTTPServer(
    httpServer,
    {
      appName: AGENT_NAME,
      currentUrl: config.publicBaseUrl,
    },
    undefined,
    false,
  );

  return {
    middleware,
    initialize: async () => {
      // No-op. The supported-kinds cache is pre-populated.
    },
  };
}

/**
 * Cancel settlement for this request — used when the audit failed after
 * payment was verified but before it settled.
 */
export function refundSettlement(res: Response): void {
  try {
    setSettlementOverrides(res, { amount: "0" });
  } catch {
    // Non-fatal.
  }
}
